### ISSUE TITLE
How to use winpe in ultimatedeployment 

### ISSUE THREAD

**Issue by laoyang103** [very-undude/ultimatedeployment#8]
Hi ultimatedeployment,

   I am new in pxe network boot, use ultimatedeployment can boot and install winxp with follow [ed2k://|file|zh-hans_windows_xp_professional_with_service_pack_3_x86_cd_x14-80404.iso|630239232|CD0900AFA058ACB6345761969CBCBFF4|/](link)

  In system page see WinPE, think it is for boot windows from network like Internet bar no disk, but I don't know what file should upload in this page, could you help me to use it?

![image](https://user-images.githubusercontent.com/6375156/140596200-32c1a6d1-ec1a-4630-bd06-55e1aba1369d.png)

**Comment by very-undude** [comment]
**Windows XP and earlier do not use WinPE for installation.** They use an older type of installation method.

More current version of Windows and later use WinPE for installations, which is the windows Pre-Execution environment. It is a very small windows distribution and runs entirely from memory. The windows installer runs inside this environment to install the actual windows distribution to your disks. Because it runs from memory it has the possibility to partition and format your disks, copy the windows files onto it, install the bootloader on there etc. Everything without rebooting... The only reboot necessary is in the end to actually boot from the disk where Windows was installed.  **If you pick Windows 7 or later for installation it will automatically use WinPE!**

When you start a PXE install with the UDA, it makes sure that the WinPE environment image (about 300-600Mb) is sent via the network to the system that you are installing. That image is loaded into memory and control is handed overto that the WinPE environment. The image only holds the WinPE environment and the installation program, and not the complete bunch of files that it needs to copy to harddisk during installation. 

The installation needs to pull those installation files from the network and to do that it needs to access a network share. That share is hosted on the UDA (which just shares the files on the ISO image you are using), but the WinPE image needs network drivers to be able to access those. For a bunch of widely used network cards those drivers are baked into the WinPE environment, but for some they are not. **You will probably not need the 'Add Windows PE Driver' screen at all**, but if your network card is not supported by the network drivers in the WinPE image, you can upload 2 files and a load script.

Here's a video where network drivers are added for use with windows 7/8 installations. Around 1:26:
https://www.youtube.com/watch?v=EgFBlhVIZDs
And here's a video where drivers are added with a more difficult driver load script:
https://www.youtube.com/watch?v=y2cO4kLxU6Q

The UDA can inject those files and the script into the WinPE image that is uploaded in the first place, and it contains hooks that automatically runs the load script before the installation is started. But again, you only need to use this if your network card is not supported by the drivers that are already available in the WinPE image.

**Comment by laoyang103** [comment]
Thanks for you reply, let me know winpe is for windows7+, but the follow video is private, can not play.

by the way could you provides how to make custom win7 pe, thans a lot

Here's a video where network drivers are added for use with windows 7/8 installations. Around 1:26:
https://www.youtube.com/watch?v=EgFBlhVIZDs
And here's a video where drivers are added with a more difficult driver load script:
https://www.youtube.com/watch?v=y2cO4kLxU6Q

**Comment by very-undude** [comment]
Ah yes, they are older videos, but I made them available again!
If you want to make a custom winpe image you should check out 

- https://win10.guru/how-to-make-a-custom-winpe/
- https://tinyapps.org/docs/custom-winpe-without-third-party.html

All the stuff that those pages do is done from Windows. The UDA uses a bunch of scripts and tools that is available in Linux. If you're starting out I'd recommend to start with Windows first. If you want to dig deeper and you are a proficient Linux user you can try to read the UDA source:
https://github.com/very-undude/ultimatedeployment/blob/main/var/public/cgi-bin/os/windows7.pl
Search for 'RunCommand' in that file to find the interesting stuff...

**Comment by laoyang103** [comment]
ok I will try, thanks a lot
